# Generated by Django 4.0.2 on 2022-04-12 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submissionDate', models.DateField()),
                ('description', models.FileField(upload_to=None)),
                ('decisionDate', models.DateField(auto_now_add=True)),
                ('comment', models.FileField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.CharField(max_length=254)),
                ('location', models.CharField(max_length=254)),
                ('lead', models.CharField(blank=True, max_length=254, null=True)),
                ('participants', models.CharField(max_length=254)),
                ('type', models.CharField(choices=[('CVPA', 'CVPA'), ('VoF', 'VoF'), ('CVI', 'CVI'), ('PMR', 'PMR'), ('Cyber Resilience', 'Cyber Resilience'), ('Individual Project', 'Individual Project'), ('Research Project', 'Research Project'), ('System Acceptance', 'System Acceptance'), ('Other', 'Other')], default='CVPA', max_length=254)),
                ('duration', models.CharField(choices=[('10 days', '10 days'), ('20 days', '20 days'), ('30 days', '30 days'), ('40 days', '40 days'), ('50 days', '50 days'), ('60 days', '60 days')], default='10 days', max_length=254)),
                ('status', models.CharField(choices=[('Pending Request Approval', 'Pending Request Approval'), ('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Past', 'Past'), ('Cancelled', 'Cancelled')], default='Pending Request Approval', max_length=254)),
                ('start_date', models.DateField(max_length=254)),
                ('end_date', models.DateField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='HardDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(null=True)),
                ('serial_number', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100, null=True)),
                ('model_number', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('connection_port', models.CharField(max_length=50, null=True)),
                ('size', models.CharField(choices=[('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('500GB', '500GB'), ('1TB', '1TB'), ('1.5TB', '1.5TB'), ('2TB', '2TB'), ('4TB', '4TB'), ('6TB', '6TB'), ('8TB', '8TB'), ('12TB', '12TB'), ('Other', 'Other')], max_length=50, null=True)),
                ('classification', models.CharField(blank=True, choices=[('Unclassified', 'Unclassified'), ('Classified', 'Classified')], max_length=50, null=True)),
                ('classification_change_justification', models.CharField(blank=True, choices=[('Text', 'Text'), ('File Attachment', 'File Attachment')], default='Text', max_length=50, null=True)),
                ('image_version_ID', models.CharField(blank=True, max_length=50, null=True)),
                ('boot_test_status', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail')], default='Pass', max_length=50, null=True)),
                ('boot_test_expiration_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Assigned', 'Assigned'), ('Available', 'Available'), ('End of Life', 'End of Life'), ('Master Clone', 'Master Clone'), ('Pending Wipe', 'Pending Wipe'), ('Destroyed', 'Destroyed'), ('Lost', 'Lost'), ('Overdue', 'Overdue'), ('Picked Up', 'Picked Up'), ('Returned', 'Returned'), ('Pending Change', 'Pending Change')], default='Available', max_length=50)),
                ('hard_drive_status_change_justification', models.CharField(blank=True, choices=[('Text', 'Text'), ('File Attachment', 'File Attachment')], default='Text', max_length=50, null=True)),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('hard_drive_return_date_justification', models.CharField(blank=True, choices=[('Text', 'Text'), ('File Attachment', 'File Attachment')], default='Text', max_length=50, null=True)),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('date_modified', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direct_supervisor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('branch_chief_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('requester_status', models.CharField(choices=[('Good Standing', 'Good Standing'), ('Delinquent', 'Delinquent'), ('Disabled', 'Disabled'), ('Archived', 'Archived')], default='Good Standing', max_length=50)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], max_length=50)),
                ('creation_date', models.DateField(max_length=254)),
                ('data_of_last_modification', models.DateField(max_length=254)),
                ('need_hard_drives_by_date', models.DateField(max_length=254)),
                ('number_of_classified_hard_drives_needed', models.PositiveIntegerField(default=0)),
                ('number_of_unclassified_hardDrives_needed', models.PositiveIntegerField(default=0)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('event', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.event')),
                ('hard_drive', models.ManyToManyField(to='website.HardDrive')),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.requester')),
            ],
        ),
        migrations.CreateModel(
            name='Maintainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('maintainer_status', models.CharField(choices=[('Active', 'Active'), ('Disabled', 'Disabled'), ('Archived', 'Archived')], default='Active', max_length=50)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('auditor_status', models.CharField(choices=[('Authorized', 'Authorized'), ('Unauthorized', 'Unauthorized'), ('Archived', 'Archived')], default='Authorized', max_length=50)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
