# Generated by Django 4.0.3 on 2022-04-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='type',
            new_name='type_of_event',
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Forecasted', 'Forecasted'), ('Cancelled', 'Cancelled')], default='Confirmed', max_length=254),
        ),
    ]
