# Generated by Django 4.0.3 on 2022-04-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_type_event_type_of_event_alter_event_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardDriveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hard_drive_classification', models.CharField(choices=[('Unclassified', 'Unclassified'), ('Classified', 'Classified')], max_length=50)),
                ('event', models.ManyToManyField(to='website.event')),
            ],
        ),
    ]
