# Generated by Django 3.2.12 on 2022-04-14 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_harddriverequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HardDriveRequest',
        ),
    ]
