# Generated by Django 4.0.4 on 2022-04-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_delete_harddriverequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardDriveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hd_classification', models.CharField(choices=[('Classified', 'Classified'), ('Unclassified', 'Unclassified')], default='Classified', max_length=50)),
                ('amount_required', models.PositiveIntegerField(default=0)),
                ('connection_port', models.CharField(choices=[('SATA', 'SATA'), ('M.2', 'M.2')], default='SATA', max_length=50)),
                ('hd_size', models.CharField(choices=[('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('500GB', '500GB'), ('1TB', '1TB'), ('1.5TB', '1.5TB'), ('2TB', '2TB'), ('4TB', '4TB'), ('6TB', '6TB'), ('8TB', '8TB'), ('12TB', '12TB'), ('Other', 'Other')], default='16GB', max_length=50)),
                ('type_of_hd', models.CharField(choices=[('Slow Hard Drive', 'Slow Hard Drive'), ('Fast Hard Drive', 'Fast Hard Drive'), ('Low-Capacity Drive', 'Low-Capacity Drive'), ('Fast-Capacity Drive', 'Fast-Capacity Drive')], default='Slow Hard Drive', max_length=50)),
                ('comment', models.CharField(blank=True, max_length=360, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('user_role', models.CharField(choices=[('Requestor', 'Requestor'), ('Auditor', 'Auditor'), ('Maintainer', 'Maintainer'), ('Admin', 'Admin')], max_length=50)),
                ('direct_supervisors_email', models.EmailField(max_length=100)),
                ('branch_chiefs_email', models.EmailField(max_length=100)),
                ('user_profile_status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Disabled', 'Disabled'), ('Archived', 'Archived')], max_length=50)),
                ('last_modified_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='lead',
            field=models.CharField(blank=True, choices=[('Vince', 'Vince'), ('Joshua', 'Joshua'), ('Dr Cheon', 'Dr Cheon'), ('Alexis', 'Alexis')], default='Vince', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.CharField(choices=[('Vince', 'Vince'), ('Joshua', 'Joshua'), ('Dr Cheon', 'Dr Cheon'), ('Alexis', 'Alexis')], default='Vince', max_length=254),
        ),
    ]
