# Generated by Django 4.0.4 on 2022-04-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_harddriverequest_userprofile_alter_event_lead_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelinquencyNotificationForOverdueHardDriveThresholdConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('notifyee', models.CharField(choices=[('Requestor', 'Requestor'), ('Maintainer', 'Maintainer'), ('Direct Supervisor', 'Direct Supervisor'), ('Branch Chief', 'Branch Chief')], max_length=50)),
                ('threshold_level', models.CharField(max_length=50)),
                ('threshold_value', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DriveInventoryThresholdConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_level', models.CharField(max_length=50)),
                ('threshold_value', models.PositiveIntegerField()),
                ('drive_inventory_threshold', models.CharField(choices=[('Unclassified', 'Unclassified'), ('Classified', 'Classified')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EventConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type_name', models.CharField(max_length=50)),
                ('length_of_reporting_cycle', models.PositiveIntegerField()),
                ('drive_limit', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ForecastedRequestNotificationThresholdConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('threshold_level', models.CharField(max_length=50)),
                ('threshold_value', models.PositiveIntegerField()),
            ],
        ),
    ]
