# Generated by Django 4.0.4 on 2022-04-17 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_delinquencynotificationforoverdueharddrivethresholdconfiguration_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delinquencynotificationforoverdueharddrivethresholdconfiguration',
            name='event_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='forecastedrequestnotificationthresholdconfiguration',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.eventconfiguration'),
        ),
    ]
