# Generated by Django 4.0.4 on 2022-04-17 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_eventconfiguration_event_type_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delinquencynotificationforoverdueharddrivethresholdconfiguration',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.eventconfiguration', to_field='event_type_name'),
        ),
    ]
